{ inputs, pkgs, ... }:

{
  imports = [
  ];
  programs.dank-material-shell = {
    enable = true;
    package = inputs.dms.packages.${pkgs.stdenv.hostPlatform.system}.default;

    niri = {
      enableKeybinds = false;   # Sets static preset keybinds
      enableSpawn = true;      # Auto-start DMS with niri, if enabled
      includes = {
        enable = true;             # Enable config includes hack. Enabled by default.

        override = true;           # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
        originalFileName = "hm";   # A new name (without extension) for the config file generated by niri-flake.
        filesToInclude = [         # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
          "alttab"                 # Please note that niri will throw an error if any of these files are missing.
          "binds"
          "colors"
          # "layout"
          "outputs"
          # "wpblur"
        ];
      };
    };

    systemd = {
      enable = true;
      restartIfChanged = true;
    };

    enableSystemMonitoring = true;
    enableDynamicTheming = true;
    enableAudioWavelength = true;
    enableCalendarEvents = true;
    enableClipboardPaste = true;
  };

}
